In [1]:
import math
import numpy as np
import sympy

#for primitive functions use sympy (i.e., sympy.cos() for cos())
def func(x):
    return x+sympy.sin(x)-1
def function2(x):
    return (x+18)**(0.5)+1-x
def function2_der(x):
    return 0.5*(x+18)**(-0.5)-1
def testfunc(x):
    return x**3-3*x**2-1-x
def testfunc_der(x):
    return 3*x**2-6*x-1

## [Fixed-point iteration method](https://en.wikipedia.org/wiki/Fixed-point_iteration)


In [2]:
def fpi(function,eps,x0):
    """
     Arguments:
        function -- equation,defined above
        eps -- const to satisfy: abs(f(c)-f(a))>=eps
        x0 -- starting x0
        Output:
        c -- equation root
        n -- number of iterations
    """
    n,x=0,x0,
    x1 = function(x)
    while(abs(x-x1)>=eps):
        n+=1
        x = x1
        x1 = function(x)

        if n%100==0:
            print(n)
    return x,n   

In [3]:
fpi(function2,0.0001,0)

(2.7791609465066296, 94)

## [Bisection method](https://en.wikipedia.org/wiki/Bisection_method)

In [5]:
def bisection(function, a,b, eps):
    """
        Arguments:
        function -- equation, defined above
        a,b  -- bounds
        eps -- precision
        Output:
        c -- equation root
        n -- number of iterations
        
    """
    def iterate():
        """
        Output:
        c -- new center of a section 
        y -- function value at new c
        """
        c = (a+b)/2.0
        y = function(c)
        return c,y
    c,y = iterate()
    n = 0
    while (y!=0 and abs(function(c)-function(a))>=eps):
        if (np.sign(y))==np.sign(function(a)):
            a=c
        else:
            b=c
        c,y = iterate()
        n+=1
        if n%100==0:
            print(n)
    return c,n

In [6]:
bisection(function2,5,6,0.0001)

(5.88751220703125, 13)

## [Newton's method](https://en.wikipedia.org/wiki/Newton%27s_method)

In [7]:
def newton_nosympy(function, derivative, x0, eps):
    """
    Arguments:
    ---------
    function - given equation
    derivative - derivative of function of given equation
    x0 - initial guess
    eps - precision
    """
    x1,x0,n = x0,function(x0),0
    while (abs(x1-x0)>=eps):
        x1,x0 = x1-function(x1)/derivative(x1),x1
        n += 1
        if n%1000==0:
            return "failure"
    return x1,n

In [8]:
def testfunc(x):
    return x**2-20*math.sin(x)
def testfunc_deriv(x):
    return 2*x-20*math.cos(x)
newton_nosympy(testfunc,testfunc_deriv,2,0.000001)

(2.752946633818705, 5)

In [9]:
def newton(function, x0, eps):
    """
    Arguments:
    function -- given equation
    x0 - initial guess
    eps - precision
    Output:
    x -- root of the equation
    n -- number of iterations
    """
    n,x0,x1 = 0,x0,0
    
    x = sympy.Symbol('x')#variable
    f = function(x)
    
    derivative = sympy.diff(f)
    
    print(derivative)
    
    x1-= float(f.subs({'x':x0}))/float(derivative.subs({'x':x0}))
    while(abs(x1-x0)>=eps):
        #x0=x1
        x1=x0 - float(function(x0))/float(derivative.subs({'x':x0})) 
        x0=x1
        n+=1
        if n%10==0:
            print("n: {0}, |x1-x0|={1}".format(n,abs(x1-x0)))
    return x1,n

### [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination)

In [10]:
def gaussian(A,b):
    """
    Arguments:
    A -- numpy.ndarray -- given system of coeffitients
    x -- numpy.ndarray -- unknown vector X 
    b -- vector b
    Output:
    x -- root of the system of equations A*x=b
    """
    n,matr = len(b),np.hstack([A,b.reshape(-1,1)])
    if np.linalg.det(A)==0: 
        return -1
    
    #direct move
    for i in range(n):
        a = matr[i]
        for j in range(i+1,n):
            b = matr[j]
            m = a[i]/b[i]
            matr[j] = a - m*b
            
    #reversed move
    for i in range(n-1,-1,-1):
        matr[i]= matr[i]/matr[i,i]
        a = matr[i]
        for j in range(i-1,-1,-1):
            b = matr[j]
            m = a[i]/b[i]
            matr[j] = a - m*b

    return matr[:,3]

In [11]:
A = np.array([[1, 2, 3], [3, 5, 7], [1, 3, 4]], dtype='float')
b = np.array([3, 0, 1])
print(gaussian(A,b))
t1,t2 = gaussian(A,b),np.linalg.solve(A,b)
t1 = np.round(t1,10)
t2 = np.round(t2,10)
np.testing.assert_array_equal(t1,t2)

[ -4. -13.  11.]


### [Cholesky decomposition](https://en.wikipedia.org/wiki/Cholesky_decomposition) a.k.a. Least Squares Method

$Ax=b$<br>

If A is symmetric & [positive-definite](https://en.wikipedia.org/wiki/Definiteness_of_a_matrix):<br>
Let $A := L*L^T$<br>

$L * y=b $ - forward substitution <br>
$L^T*x=y $  - back substitution<br><br>

LDLT decomposition:<br>

Let $A:= L * D * L^T$<br>
$L * y = b $<br>
$DL* x = y $

In [12]:
def ldl_decomposition(A):
    L_cholesky = np.linalg.cholesky(A)
    S = L_cholesky.diagonal()
    D = S**2
    S_inv = np.linalg.inv(np.diagflat(S))
    L = np.dot(L_cholesky,S_inv)
    return L,D
def cholesky(A,b):
    if np.array_equal(A,A.T):
        try:
            L = np.linalg.cholesky(A)
            y = np.linalg.solve(L,b)
            x = np.linalg.solve(L.T,y)
        except np.linalg.LinAlgError:
            return "Unsutable matrix"
    return x

In [13]:
T = np.array([[4,12,-16],[12,37,-43],[-16,-43,98]])
A,b = np.array([[25,15,-5],[15,18,0],[-5,0,11]]),np.array([-2,0.25,10.2])
cholesky(A,b)
ldl_decomposition(T)

(array([[ 1.,  0.,  0.],
        [ 3.,  1.,  0.],
        [-4.,  5.,  1.]]), array([4., 1., 9.]))

### [Tridiagonal matrix algorithm](https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm)

In [20]:
def get_coeff_vect(array):
    """
    Arguments:
    ----------
    array -- array of shape(n,n)
    returns triagonals a,b,c
    Output:
    a,b,c -- tridiagonals of an array
    """
    n = len(array)
    ind1,ind2 = [i for i in range(1,n)],[i-1 for i in range(1,n)]
    a = np.copy(array[ind1,ind2])
    b = np.copy(array[[i for i in range(n)],[i for i in range(n)]])
    c = np.copy(array[ind2,ind1])
    return a,b,c


def tridiagonal_matr_algo(arr,f,local_coeff=False,flag=False,a=None,b=None,c=None):
    """
    Arguments:
    ----------
    arr -- array of shape(n,n)
    f -- vector of shape(n,)
    local_coeff -- bool, uses slighty different calculations
    Output:
    x -- solution of system of equations A*x = f
    """
    n,f= len(arr),np.copy(f)  
    if not flag:  
        a,b,c = get_coeff_vect(arr)

    
    if local_coeff:
        alpha,beta = [],[]
        alpha.append(c[0]/b[0])
        beta.append(f[0]/b[0])
        
        #forward step
        for i in range(1,n):
            if i!=n-1:
                alpha.append(c[i]/(b[i]-alpha[-1]*a[i-1]))
            beta.append((f[i]-beta[-1]*a[i-1])/(b[i]-alpha[-1]*a[i-1]))

        
        #backward step
        x = beta
        for i in reversed(range(n-1)):
            x[i] = beta[i]-alpha[i]*x[i+1]
        
        return x
    else: 
        # forward step
        for i in range(1,n):
            w = a[i-1]/b[i-1]
            b[i] -= w*c[i-1]
            f[i] -= w*f[i-1]
        #backward step
        x = b
        x[-1] = f[-1]/b[-1]
        for i in range(n-2,-1,-1):
            x[i]=(f[i]-c[i]*x[i+1])/(b[i])
        return x   

In [21]:
A,b = np.array([[4.610,1.700,0,0,0],[1.32,4.16,1.34,0,0],[0,1.62,4.32,1.08,0],[0,0,1.58,4.85,1.39],[0,0,0,1.71,4.31]],dtype=float),np.array([10.92,6.8,2.7,4.85,1.71])
tridiagonal_matr_algo(A,b)

array([2.00000000e+00, 1.00000000e+00, 5.95450001e-17, 1.00000000e+00,
       0.00000000e+00])

In [4]:
#A,d = np.array([[-4,1,0,0],[1,-4,-1,0],[0,1,-4,1],[0,0,1,-4]],dtype=float),np.array([-6,-4,-4,-6],dtype=float)
A,b = np.array([[4.77,1.28,0,0,0],[1.78,4.12,1.66,0,0],[0,1.57,4.16,1.92,0],[0,0,1.08,4.72,1.38],[0,0,0,1.31,4.65]],dtype=float),np.array([7.33,13.34,11.46,2.16,0])
tridiagonal_matr_algo(A,b)

array([1., 2., 2., 0., 0.])

In [18]:
C,d = np.array([[-4,1,0,0],[1,-4,1,0],[0,1,-4,1],[0,0,1,-4]],dtype=float),np.array([-6,-4,-4,-6],dtype=float)
print("TMA, no local coefficient preservation: {0}".format(tridiagonal_matr_algo(C,d)))
print("TMA, local coefficient preservation:{0}".format(tridiagonal_matr_algo(C,d,True)))
print("Standard Gaussian solver: {0}".format(np.linalg.solve(C,d)))

TMA, no local coefficient preservation: [2. 2. 2. 2.]
TMA, local coefficient preservation:[2.001795631286786, 2.0071825251471433, 2.002380897873217, 2.000595224468304]
Standard Gaussian solver: [2. 2. 2. 2.]


### [Jacobi method](https://en.wikipedia.org/wiki/Jacobi_method)

In [18]:
def dd(A):
    D = np.diag(A)
    S = np.abs(A - np.diagflat(D))
    D = (D * np.ones((D.shape[0],D.shape[0]))).T
    if np.all(D > S):
        print('matrix is diagonally dominant')
        return True
    else:
        print('NOT diagonally dominant')
        return False

def spectre(A):
    D = np.diagflat(np.diag(A))
    R = A - D
    rho = np.sum(np.abs(np.dot(np.linalg.inv(D),R)),axis=1)
    if np.all(rho<np.ones(rho.shape[0])):
        print('Spectral radius <1')
        print(rho)
        return True
    print('Spectral radius > 1')
    return False

def jacobi(A,b,iters=4,eps=10e-4):
    alpha = A - np.diagflat(np.diag(A))
    x = np.zeros(len(A))
    if dd(A) and spectre(A):
        for i in range(iters):
            x_new = (b - np.dot(alpha,x))/np.diag(A)
            if np.allclose(x, x_new, atol=eps):
                print('Reached convergence. Solution is:')
                return x_new,i
            x = x_new
    return x

In [19]:
A,b = np.array([[36,-9,-3],[-9,38.25,-5.25],[-3,-5.25,10.25]]),np.array([93,54.75,-29.75])
jacobi(A,b,1200)

matrix is diagonally dominant
Spectral radius <1
[0.33333333 0.37254902 0.80487805]
Reached convergence. Solution is:


(array([ 2.9998062 ,  1.99978199, -1.0003793 ]), 10)

In [6]:
A = np.array([[2/3,1/6,0],[1/6,2/3,1/6],[0,1/6,2/3]],dtype=float)
b = np.array([5/6,1,5/6])
jacobi(A,b,iters=10)

matrix is diagonally dominant
Spectral radius <1
Reached convergence. Solution is:


array([1.00006104, 1.00012207, 1.00006104])

### [Seidel method](https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method)

$Ax = b$<br>

$L_* $ - lower triangular component of A <br>
$U $  - strict upper triangular component of A<br><br>
$T = -L_*^{-1}U$<br>
$C=L_*^{-1}b$<br>

iteratively, $x^{(k+1)}=Tx^{(k)}+C$

In [21]:
def seidel(A,b,x0,eps):
    """
    Arguments:
    A -- array of shape(n,n)
    b -- array of shape(n,1)
    x0 -- initial guess - array of shape(n)
    eps -- precision
    Returns:
    x1 -- array of shape(n,)
    n -- number of iterations
    """
    L,U = np.tril(A),np.triu(A,1)
    L_inv = np.linalg.inv(L)
    
    T,C = np.dot(-L_inv,U), np.dot(L_inv,b)
    
    n, x1 = 0, np.dot(T,x)+C
    while not np.allclose(x0,x1,rtol=eps):
        x0 = x1
        x1 = np.dot(T,x0)+C
        n+=1
        if n==1000:
            return "smth went wrong"
    return x1,n

In [57]:
A,b = np.array([[36,-12,9],[-12,29,12],[9,12,27.5]],dtype=float),np.array([-81,12,-45.25])
x = np.array([1,1,1],dtype=float)
seidel(A,b,x,1e-3)

(array([-2.00693063, -0.00923843, -0.98460957]), 18)

In [64]:
A,b = np.array([[36,6,12],[6,10,0.5],[12,0.5,20.25]],dtype=float),np.array([30,35,-27])
x = np.array([1,1,1],dtype=float)
seidel(A,b,x,1e-9)

(array([ 1.,  3., -2.]), 15)

In [86]:
C,d = np.array([[2/3,1/6,0],[1/6,2/3,1/6],[0,1/6,2/3]],dtype=float),np.array([5/6,1,5/6]) 
x = np.array([0,0,0],dtype=float)
seidel(C,d,x,1e-7)

(array([1., 1., 1.]), 9)

## [Lagrange polynomial interpolation](https://en.wikipedia.org/wiki/Lagrange_polynomial)

In [7]:
#correct implementation: fit using train, generate an equation, then use it to evaluate test
def LagrangePolynomial_fit(X,Y):
    x,n = sympy.Symbol('x'),len(X)
    function = 0
    for i in range(n):
        def L(i):
            Lv = 1
            for j in range(n):
                if i!=j:
                    Lv*=(x - X[j])/(X[i]-X[j])
            return Lv
        function+=Y[i]*L(i)
    return function
def LagrangePolynomial_predict(x,function):
    return function.subs({'x':x})

## Chebyshev polynomial interpolation